from flask import Flask, request, jsonify, send_file
from flask_cors import CORS
import google.generativeai as genai
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.units import inch
import io
import json
import re
import threading
import time

app = Flask(__name__)
CORS(app)

# Gemini config
GEMINI_API_KEY = "AIzaSyD1CaHNkeZ0GgG-kFlTZv3GK0p-DCSKqBM"
genai.configure(api_key=GEMINI_API_KEY)
model = genai.GenerativeModel("gemini-2.5-flash")

PROMPT_TEMPLATE = """You are a TNEA (Tamil Nadu Engineering Admissions) counseling expert.

Based on the following student details, suggest the best colleges and departments they can get admitted to.

Student Details:
- Cutoff Mark: {cutoff}
- Community/Category: {category}
- Preferred District/Region: {region}
- Number of suggestions needed: {count}

Rules:
- Suggest REAL Tamil Nadu engineering colleges with correct names
- Consider the cutoff mark and community reservation
- Include a mix of government, government-aided, and self-financing colleges appropriate for the cutoff
- For each suggestion give: College Name, Department, Expected Cutoff Range, College Type (Govt/Aided/Self-Finance), Location

Return ONLY a valid JSON array with exactly {count} objects. Each object must have these keys:
"college", "department", "cutoff_range", "college_type", "location"

No markdown, no explanation, just the JSON array.
"""

def wrap_cell(text, style):
    """Wrap text in Paragraph so it breaks to next line when too long."""
    return Paragraph(str(text).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"), style)

def generate_pdf(student_info, colleges):
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=landscape(A4), topMargin=30, bottomMargin=30, leftMargin=25, rightMargin=25)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("Title2", parent=styles["Title"], fontSize=18, textColor=colors.HexColor("#1a237e"), alignment=1)
    sub_style = ParagraphStyle("Sub", parent=styles["Normal"], fontSize=11, textColor=colors.HexColor("#333333"), spaceAfter=4, alignment=1)
    cell_style = ParagraphStyle("Cell", fontName="Helvetica", fontSize=8, leading=11, alignment=0, splitLongWords=1, wordWrap='CJK')
    cell_center = ParagraphStyle("CellC", fontName="Helvetica", fontSize=8, leading=11, alignment=1, splitLongWords=1, wordWrap='CJK')
    header_style = ParagraphStyle("Header", fontName="Helvetica-Bold", fontSize=9, leading=12, textColor=colors.white, alignment=1)
    elements = []

    elements.append(Paragraph("TNEA College Choice List", title_style))
    elements.append(Spacer(1, 10))
    elements.append(Paragraph(f"Cutoff: {student_info['cutoff']} &nbsp;|&nbsp; Category: {student_info['category']} &nbsp;|&nbsp; Region: {student_info['region']}", sub_style))
    elements.append(Spacer(1, 14))

    header = [wrap_cell(h, header_style) for h in ["#", "College Name", "Department", "Cutoff Range", "Type", "Location"]]
    data = [header]
    for i, c in enumerate(colleges, 1):
        data.append([
            wrap_cell(i, cell_center),
            wrap_cell(c.get("college", ""), cell_style),
            wrap_cell(c.get("department", ""), cell_style),
            wrap_cell(c.get("cutoff_range", ""), cell_center),
            wrap_cell(c.get("college_type", ""), cell_center),
            wrap_cell(c.get("location", ""), cell_style),
        ])

    pw = landscape(A4)[0] - 50
    col_widths = [pw*0.04, pw*0.34, pw*0.20, pw*0.14, pw*0.14, pw*0.14]
    table = Table(data, colWidths=col_widths, repeatRows=1, splitInRow=1)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a237e")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.HexColor("#f5f5f5"), colors.white]),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(table)
    elements.append(Spacer(1, 20))
    elements.append(Paragraph("Generated by TNEA Choice List Maker | AI-powered suggestions — verify with official TNEA data.",
                              ParagraphStyle("Foot", fontName="Helvetica", fontSize=8, textColor=colors.grey, alignment=1)))
    doc.build(elements)
    buf.seek(0)
    return buf



@app.route("/", methods=["GET"])
def home():
    return """
    <html>
    <head><title>TNEA Choice List Maker</title>
    <style>
        * { margin:0; padding:0; box-sizing:border-box; }
        body { font-family:'Segoe UI',sans-serif; background:linear-gradient(135deg,#667eea,#764ba2); min-height:100vh; display:flex; align-items:center; justify-content:center; }
        .card { background:#fff; border-radius:16px; padding:40px; width:420px; box-shadow:0 20px 60px rgba(0,0,0,0.3); }
        h1 { color:#1a237e; font-size:22px; margin-bottom:6px; }
        p.sub { color:#666; font-size:13px; margin-bottom:24px; }
        label { display:block; font-size:13px; color:#333; margin-bottom:4px; font-weight:600; }
        input,select { width:100%; padding:10px 12px; border:1.5px solid #ddd; border-radius:8px; font-size:14px; margin-bottom:16px; outline:none; }
        input:focus,select:focus { border-color:#667eea; }
        button { width:100%; padding:12px; background:linear-gradient(135deg,#667eea,#764ba2); color:#fff; border:none; border-radius:8px; font-size:15px; cursor:pointer; font-weight:600; }
        button:hover { opacity:0.9; }
        button:disabled { opacity:0.5; cursor:wait; }
        .msg { text-align:center; margin-top:12px; font-size:13px; color:#666; }
    </style></head>
    <body>
    <div class="card">
        <h1>TNEA Choice List Maker</h1>
        <p class="sub">AI-powered college suggestions based on your cutoff</p>
        <form id="f">
            <label>Cutoff Mark</label>
            <input type="number" id="cutoff" step="0.01" max="200" min="0" placeholder="e.g. 185.5" required>
            <label>Community / Category</label>
            <select id="category" required>
                <option value="">Select</option>
                <option>OC</option><option>BC</option><option>BCM</option>
                <option>MBC</option><option>SC</option><option>SCA</option><option>ST</option>
            </select>
            <label>Preferred Region</label>
            <select id="region" required>
                <option value="">Select</option>
                <option>Chennai</option><option>Coimbatore</option><option>Madurai</option>
                <option>Trichy</option><option>Salem</option><option>Tirunelveli</option>
                <option>Vellore</option><option>Thanjavur</option><option>Any</option>
            </select>
            <label>Number of Suggestions</label>
            <input type="number" id="count" min="1" max="30" value="10" required>
            <button type="submit" id="btn">Generate PDF Choice List</button>
        </form>
        <div class="msg" id="msg"></div>
    </div>
    <script>
    document.getElementById("f").onsubmit = async function(e) {
        e.preventDefault();
        const btn = document.getElementById("btn"), msg = document.getElementById("msg");
        btn.disabled = true; btn.textContent = "Generating..."; msg.textContent = "";
        try {
            const res = await fetch("/generate", {
                method: "POST", headers: {"Content-Type":"application/json"},
                body: JSON.stringify({
                    cutoff: document.getElementById("cutoff").value,
                    category: document.getElementById("category").value,
                    region: document.getElementById("region").value,
                    count: document.getElementById("count").value
                })
            });
            if (!res.ok) { const err = await res.json(); throw new Error(err.error || "Failed"); }
            const blob = await res.blob();
            const url = URL.createObjectURL(blob);
            const a = document.createElement("a"); a.href = url; a.download = "tnea_choice_list.pdf"; a.click();
            msg.textContent = "PDF downloaded!";
        } catch(err) { msg.textContent = "Error: " + err.message; }
        btn.disabled = false; btn.textContent = "Generate PDF Choice List";
    };
    </script>
    </body></html>
    """

@app.route("/generate", methods=["POST"])
def generate():
    data = request.json
    cutoff = data.get("cutoff", "")
    category = data.get("category", "")
    region = data.get("region", "Any")
    count = int(data.get("count", 10))

    if not cutoff or not category:
        return jsonify({"error": "cutoff and category are required"}), 400

    prompt = PROMPT_TEMPLATE.format(cutoff=cutoff, category=category, region=region, count=count)

    try:
        response = model.generate_content(prompt)
        text = response.text.strip()
        # Clean markdown fences if present
        text = re.sub(r"^```(?:json)?\s*", "", text)
        text = re.sub(r"\s*```$", "", text)
        colleges = json.loads(text)
    except Exception as e:
        return jsonify({"error": f"Gemini API error: {str(e)}"}), 500

    student_info = {"cutoff": cutoff, "category": category, "region": region}
    pdf_buf = generate_pdf(student_info, colleges)

    return send_file(pdf_buf, mimetype="application/pdf", as_attachment=True, download_name="tnea_choice_list.pdf")


if __name__ == "__main__":
    # Start ngrok tunnel in background
    def start_ngrok():
        time.sleep(2)
        try:
            from pyngrok import ngrok
            tunnel = ngrok.connect(5000)
            print(f"\n{'='*50}")
            print(f"  NGROK LIVE URL: {tunnel.public_url}")
            print(f"{'='*50}\n")
        except Exception as e:
            print(f"\nNgrok error: {e}")
            print("Install pyngrok: pip install pyngrok")
            print("App still running at http://localhost:5000\n")

    threading.Thread(target=start_ngrok, daemon=True).start()
    app.run(host="0.0.0.0", port=5000, debug=False)
